### ISSUE TITLE
你好我是Ruby、Android萌新:joy:

### ISSUE THREAD

**Issue by ice1000** [raymondmars/tech-forum-on-android#1]
我想完整地看看这个项目学习一下。。<br/>
请问我应该从哪里看起？（尚未学过Android网络编程:joy:）组件还是Layouts，还是工具类那些？

**Comment by raymondmars** [comment]
从基础的layout看起吧。

**Comment by ice1000** [comment]
从布局看起？:astonished: 那Java那边呢、工具类和四大组件？
